### ISSUE TITLE
Replace axios client with fetch

### ISSUE THREAD

**Issue by emptycurse** [print4health/print4health#208]
As i know you can send any kind of request with fetch and there is no need for an external client or package. To keep the dependecies light we should replace it with fetch and remove axios client.

**Comment by BoyPersoon** [comment]
@emptycurse I see our Webpack configuration doesn't have a polyfill for the Fetch configured (or does it?). The axios library provides support for IE and older browsers. If this is a global project that will be used by large institutions that might not have up to date browsers maybe we should stick to Axios?

Can I use on Fetch below:
<img width="1174" alt="Screenshot 2020-03-31 at 20 38 50" src="https://user-images.githubusercontent.com/18622217/78063052-e0f6a700-738f-11ea-8189-a57142a21df3.png">

**Comment by emptycurse** [comment]
https://www.npmjs.com/package/react-app-polyfill,
https://babeljs.io/docs/en/presets

**Comment by bartrail** [comment]
branch feature/axios-replace 
@emptycurse might finish it later :D 

another issue might be that cypress tests couldt not work with fetch api for now https://docs.cypress.io/guides/guides/network-requests.html#Testing-Strategies
