### ISSUE TITLE
Usability: Add text to the most important buttons

### ISSUE THREAD

**Issue by lthamm** [print4health/print4health#215]
The button to claim the need for an item does not have any text on it and show a white cross on a red background, this looks like a swiss or hospital icon but not like a ui element. 

- Buttons shall have a text that indicate what they are for ("Order items") 
- Important buttons shall be positioned below, not next to text, e.g headline, description, button
- Buttons shall have consistent colors according to their function.

**Comment by bartrail** [comment]
Sounds great! :) I'll see what I can do.
Could you point me to Buttons that are inconsistent with each other according to their function please? Maybe I just dont see the wood for the trees...

**Comment by lthamm** [comment]
e.g. here https://print4health.org/#/thing/3bed1228-fa2a-459b-8472-6e13fd0d362e

Red means open menu for "Bedarf" and after clicking "Ok" means close window. Maybe red is supposed to be the primary cta?
