### ISSUE TITLE
Refactor add command bus

### ISSUE THREAD

**Issue by dragonito** [print4health/print4health#86]
Wäre super wenn wir das Ganze noch mal etwas strukturieren könnten.

* Domainenstruktur anlegen
* CommandBus implementieren

Kann das gerne übernehmen sobald wir die erste lauffähige Version haben

**Comment by bartrail** [comment]
vielleicht sollten wir das trennen:
1. **jetzt:** domain/infrastructure sinngemäß trennen
2. **später:** command bus da wo es sinnvoll ist irgendwann in der zukunft. Ich habe nochmal drüber nachgedacht und denke wir sollten nicht Hals über Kopf den Command Bus einbauen nur weil es geht ;)

**Comment by dragonito** [comment]
Domainstruktur ist angelegt
