### ISSUE TITLE
Implement things-list Search function

### ISSUE THREAD

**Issue by gherkins** [print4health/print4health#94]
the listt of things should be filterable as the search input suggests.

**Comment by GoodGuyMarco** [comment]
1. should this happen in frontend or backend e.g. via endpoint?
2. what properties should be considered for the search?

**Comment by bartrail** [comment]
1. I think there should be an endpoint for that. right now a `query` parameter should be sufficient
2. thing.name and thing.description - we don't have any other properties

**Comment by GoodGuyMarco** [comment]
I could implement that as soon as the endpoint is provided.

**Comment by bartrail** [comment]
I just made a ticket for it #100 and will do it later today

**Comment by GoodGuyMarco** [comment]
Gonna do frontend today, what's the endpoints url and query params? @bartrail
